# .github/workflows/ci_cd.yml

name: CI Pipeline

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the 'main' branch

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python app.py

      - name: Generate MLflow Parameter csv
        run: |
          # install mlflow
          pip install mlflow
          # collect MLflow tracking parameter and save as csv
          python Generate_mlflow_parameter.py



      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"